import{configured,supabase}from'./supabase';import type{InventoryRow,Item}from'./types';export{configured}from'./supabase';

export const client=()=>{if(!configured||!supabase)throw Error('Connect Supabase to continue. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to .env.local.');return supabase};
export function address(i:InventoryRow){return i.boxes?`${i.boxes.locations.name} · Box ${i.boxes.box_number}${i.boxes.description?` — ${i.boxes.description}`:''}`:i.locations?.name??'No location';}
export async function listItems(opts:{search:string;location:string;box:string;tag:string;archived:boolean;out:boolean;page:number;pageSize?:number}){const db=client(),lo=opts.page*(opts.pageSize??30),hi=lo+(opts.pageSize??30)-1;let q=db.from('items').select('*,locations(*),boxes(*,locations(*)),item_photos(*)',{count:'exact'}).order('created_at',{ascending:false}).order('sort_order',{referencedTable:'item_photos',ascending:true}).range(lo,hi).eq('archived',opts.archived);if(opts.search.trim()){const{data,error}=await db.rpc('search_item_ids',{search_text:opts.search.trim()});if(error)throw error;if(!data?.length)return{items:[],count:0};q=q.in('id',data);}if(opts.location){const{data,error}=await db.rpc('item_ids_at_location',{target_location_id:opts.location});if(error)throw error;if(!data?.length)return{items:[],count:0};q=q.in('id',data);}if(opts.box)q=q.eq('box_id',opts.box);if(opts.tag)q=q.contains('tags',[opts.tag]);if(opts.out)q=q.eq('quantity',0);const{data,error,count}=await q;if(error)throw error;return{items:(data??[])as unknown as InventoryRow[],count:count??0};}
export async function saveItem(item:Partial<Item>&{name:string},expected?:number){const db=client(),payload={...item,version:(expected??0)+1};const{data,error}=item.id?await db.from('items').update(payload).eq('id',item.id).eq('version',expected??0).select().maybeSingle():await db.from('items').insert(payload).select().single();if(error)throw error;if(!data)throw Error('This item changed elsewhere. Reload it and apply your edits again.');return data;}
export async function savePhoto(itemId:string,path:string,order:number){return client().from('item_photos').insert({item_id:itemId,object_path:path,sort_order:order,is_cover:order===0}).select().single();}
export async function setPhotoOrder(itemId:string,orderedIds:string[],coverId:string){const{error}=await client().rpc('reorder_item_photos',{target_item_id:itemId,ordered_photo_ids:orderedIds,cover_photo_id:coverId});if(error)throw error;}
export async function removePhotoRecord(photoId:string){const db=client(),{data,error}=await db.from('item_photos').delete().eq('id',photoId).select('object_path').single();if(error)throw error;const result=await db.storage.from('inventory-photos').remove([data.object_path]);return result.error?`Photo metadata was removed, but storage cleanup failed for ${data.object_path}: ${result.error.message}`:null;}
export async function uploadPhoto(itemId:string,file:File){const db=client(),blob=await compressImage(file),path=`${(await db.auth.getUser()).data.user!.id}/${itemId}/${crypto.randomUUID()}.jpg`;const{error}=await db.storage.from('inventory-photos').upload(path,blob,{contentType:'image/jpeg',upsert:false});if(error)throw Error(`Upload failed or had an uncertain response (${error.message}). If the object exists, check/remove ${path} from the private bucket before retrying.`);const current=await db.from('item_photos').select('sort_order').eq('item_id',itemId).order('sort_order',{ascending:false}).limit(1);if(current.error){const cleanup=await db.storage.from('inventory-photos').remove([path]);throw Error(cleanup.error?`Could not read saved photo order (${current.error.message}); cleanup also failed. Remove ${path} from your private bucket after the interruption.`:`Could not read saved photo order (${current.error.message}); uploaded object was cleaned up.`);}const order=(current.data?.[0]?.sort_order??-1)+1;const result=await savePhoto(itemId,path,order);if(result.error){const cleanup=await db.storage.from('inventory-photos').remove([path]);throw Error(cleanup.error?`Photo metadata failed (${result.error.message}); storage cleanup also failed. Remove ${path} from your private bucket after the interruption.`:`Photo metadata failed (${result.error.message}); uploaded object was cleaned up.`);}return result.data;}
async function compressImage(file:File){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error(`${file.name}: use JPEG, PNG or WebP. HEIC/HEIF is not supported by this browser.`);const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});const scale=Math.min(1,2048/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Could not process image')), 'image/jpeg',.88));}
export async function photoUrl(path:string){const{data,error}=await client().storage.from('inventory-photos').createSignedUrl(path,300);if(error)throw error;return data.signedUrl;}
export async function fetchAllPages<T>(fetchPage:(from:number,to:number)=>Promise<{data:T[]|null;error:unknown}>,pageSize=500){const all:T[]=[];for(let from=0;;from+=pageSize){const{data,error}=await fetchPage(from,from+pageSize-1);if(error)throw error;all.push(...(data??[]));if((data??[]).length<pageSize)break;}return all;}
export async function exportRows(){const db=client(),tables=['locations','boxes','items','item_photos'] as const,out:Record<string,unknown[]>={};for(const t of tables)out[t]=await fetchAllPages(async(from,to)=>db.from(t).select('*').range(from,to));return{schema:'home-storage-inventory',version:1,exported_at:new Date().toISOString(),data:out};}
export async function exportZip(progress:(s:string)=>void,destination?:WritableStream<Uint8Array>):Promise<Blob|null>{const{writeInventoryZip}=await import('./archive'),archive=await exportRows(),photos=archive.data.item_photos as Array<{object_path:string;id:string}>;return writeInventoryZip(archive,photos,async photo=>{const url=await photoUrl(photo.object_path),response=await fetch(url,{cache:'no-store'});if(!response.ok||!response.body)throw Error(`Photo download failed (${response.status}) for ${photo.object_path}; backup incomplete.`);return response.body},progress,destination);}
